box_perception:
  ros__parameters:
    box_a_1_position: [1.2, 2.3, 0.0]
    box_a_2_position: [1.5, 2.3, 0.0]
    box_a_3_position: [1.8, 2.3, 0.0]
    box_a_4_position: [2.1, 2.3, 0.0]
    box_a_5_position: [2.4, 2.3, 0.0]
    box_a_6_position: [2.7, 2.3, 0.0]
    box_a_7_position: [3.0, 2.3, 0.0]
    box_a_8_position: [3.3, 2.3, 0.0]
    box_a_9_position: [3.6, 2.3, 0.0]
    box_a_10_position: [3.9, 2.3, 0.0]
    box_b_1_position: [7.0, 5.225, 0.144]
    box_b_2_position: [7.4, 5.225, 0.144]
    box_b_3_position: [7.8, 5.225, 0.144]
    box_b_4_position: [2.1, 2.6, 0.0]
    box_b_5_position: [2.4, 2.6, 0.0]
    box_b_6_position: [2.7, 2.6, 0.0]
    box_b_7_position: [3.0, 2.6, 0.0]
    box_b_8_position: [3.3, 2.6, 0.0]
    box_c_1_position: [9.75, 5.225, 0.144]
    box_c_2_position: [10.0, 5.225, 0.644]
    box_c_3_position: [10.25, 5.225, 0.144]
    box_c_4_position: [2.1, 2.9, 0.0]
    box_c_5_position: [2.4, 2.9, 0.0]
    box_d_1_position: [8.1, 5.225, 0.144]
    box_d_2_position: [8.3, 5.225, 0.144]
    box_d_3_position: [8.5, 5.225, 0.144]
    box_e_1_position: [8.75, 5.225, 0.144]
    box_e_2_position: [9.05, 5.225, 0.144]
    box_e_3_position: [9.35, 5.225, 0.144]