pure_pursuit:
  ros__parameters:
    angle_p: 5.0
    angle_lookahead_distance: 0.7
    lookahead_time: 1.0
    curve_decceleration_p: 5.0
    goal_deceleration_distance_m: 0.3
    max_acceleration_xy_m_s2_: 1.0