pure_pursuit:
  ros__parameters:
    lookahead_time: 1.0
    min_lookahead_distance: 0.05
    max_lookahead_distance: 1.0
    curvature_decceleration_p: 1.0
    goal_deceleration_distance_p: 10.0
    goal_deceleration_p: 30.0
    max_acceleration_xy_m_s2_: 10.0
    max_speed_xy_m_s: 2.0
    max_speed_z_rad_s: 3.14
    angle_p: 2.0
    angle_lookahead_distance: 2.0
    max_acceleration_z_rad_s2: 6.28

velocity_smoother:
  ros__parameters:
    max_acceleration: 8.0
