site_name: nhk2025b_ros2
site_url: https://github.com/NITIC-Robot-Club/nhk2025b_ros2
repo_url: https://github.com/NITIC-Robot-Club/nhk2025b_ros2
edit_uri: https://github.com/NITIC-Robot-Club/nhk2025b_ros2
theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  language: ja
  palette:
    - scheme: slate  # ダークテーマ
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: ライトモードに切り替え

    - scheme: default  # ライトテーマ
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: ダークモードに切り替え

nav:
  - Home: index.md
  - src:
      - behavior:
          - behavior: src/behavior/nhk2025b_behavior
      - common:
          - canable: src/common/nhk2025b_canable
          - map_publisher: src/common/nhk2025b_map_publisher
      - control:
          - pure_pursuit: src/control/nhk2025b_pure_pursuit
          - swerve_calculator: src/control/nhk2025b_swerve_calculator
      - launch:
          - launch: src/launch/nhk2025b_launch
      - localization:
          - ekf: src/localization/nhk2025b_ekf
          - mcl: src/localization/nhk2025b_mcl
          - pose_initializer: src/localization/nhk2025b_pose_initializer
          - wheel_odometry: src/localization/nhk2025b_wheel_odometry
      - message:
          - msgs: src/message/nhk2025b_msgs
      - planning:
          - path_planner: src/planning/nhk2025b_path_planner
      - simulation:
          - simulation: src/simulation/nhk2025b_simulation
      - visualization:
          - footprint_publisher: src/visualization/nhk2025b_footprint_publisher
          - visualize_swerve: src/visualization/nhk2025b_visualize_swerve

# README.md をトップページとして使う場合
docs_dir: docs

markdown_extensions:
  - admonition             # !!! note などでアラートブロック
  - codehilite             # コードハイライト
  - toc:                   # 目次の自動生成（右サイド）
      permalink: true
  - tables                 # 表の拡張
  - footnotes              # 脚注機能
  - abbr                   # 略語の補足
  - def_list               # 定義リスト（: を使うやつ）
  - attr_list              # HTML属性をマークダウン内で使用可能

  # pymdownx 拡張（Materialテーマ推奨）
  - pymdownx.superfences   # ネストされたコードブロック
  - pymdownx.tabbed:       # タブ表示の強化
      alternate_style: true
  - pymdownx.details       # 折りたたみ詳細ブロック
  - pymdownx.emoji         # :smile: のような絵文字
  - pymdownx.tasklist      # チェックボックスリスト
  - pymdownx.highlight     # ハイライト強化
  - pymdownx.inlinehilite  # インラインハイライト
  - pymdownx.magiclink     # URLを自動リンク化
  - pymdownx.caret         # ^上付き文字^
  - pymdownx.mark          # ==マーク==（蛍光ペン風）
  - pymdownx.tilde         # ~~取り消し線~~
