<?xml version="1.0"?>
<package format="3">
  <name>nhk2025b_icp</name>
  <version>0.0.1</version>
  <description>ICPによるLidarと地図のマッチングで自己位置推定を行うパッケージ</description>
  <maintainer email="your@email.com">your_name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nhk2025b_utils</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
