<?xml version="1.0"?>
<package format="3">
  <name>nhk2025b_joint_state_publisher</name>
  <version>0.0.1</version>
  <description>joint_state_publisher</description>
  <maintainer email="0.hk777700@gmail.com">hk</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nhk2025b_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>