name: c++ style auto fix and colcon build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  auto_fix_and_build:
    permissions:
      contents: write

    strategy:
      matrix:
        os: 
          - ubuntu-22.04
        rosdistro: 
          - humble

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: nhk2025b_ros2

      - name: Install dependencies
        working-directory: nhk2025b_ros2
        run: |
          rosdep update
          apt-get update
          apt-get install -y curl lsb-release
          apt-get install -y clang clang-format
          apt-get install -y cmake
          rosdep install --from-path src -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Install diagnostic-updater
        working-directory: nhk2025b_ros2
        run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Run clang-format (auto-fix)
        working-directory: nhk2025b_ros2
        run: |
          find src -regex '.*\.\(cpp\|hpp\|h\)' -exec clang-format -i {} +

      - name: Commit and push changes
        working-directory: nhk2025b_ros2
        run : |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git checkout ${{ github.head_ref }}
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-fix: applied clang-format and clang-tidy"
            git push
          fi

      - name: Build tests
        id: build_test
        working-directory: nhk2025b_ros2
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
        continue-on-error: true

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1