name: colcon build all packages

on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - labeled
      - ready_for_review 
  workflow_dispatch:

jobs:
  build_full:

    strategy:
      matrix:
        os: 
          - ubuntu-22.04
        rosdistro: 
          - humble

    runs-on: ubuntu-latest

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    if: |
      (github.event_name == 'labeled' && github.event.label.name == 'run_build') ||
      (github.event_name != 'labeled')

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: nhk2025b_ros2

      - name: Install dependencies
        working-directory: nhk2025b_ros2
        run: |
          rosdep update
          apt-get update
          rosdep install --from-path src -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Build tests
        id: build_test
        working-directory: nhk2025b_ros2
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh && 
          colcon build
        continue-on-error: true

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1