name: Build and Push nhk2025b_ros2 to GHCR

on:
  push:
    branches:
      - 113-feat-actions-add-docker
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時（UTC）

permissions:
  contents: read
  packages: write  # GHCR への Push に必要

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nhk2025b_ros2:latest
          labels: |
            org.opencontainers.image.title=nhk2025b_ros2
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
