name: Deploy MkDocs

on:
  push:
    branches:
      - 104-feat-readme-mkdocs-deploy 
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout 104-feat-readme-mkdocs-deploy 
          git branch mkdocs-deploy
          git checkout mkdocs-deploy

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions mkdocs-awesome-pages-plugin mkdocs-same-dir

      - name: Prepare markdown
        run: |
          mkdir -p docs

          cp README.md docs/index.md
          cp .pages docs/.pages

          # src以下のすべてのmdファイルを探す
          find src -name "*.md" | while read -r filepath; do
            # 例: filepath=src/test/my_package_test/README.md

            # ベースディレクトリを除いた相対パスを作る
            relative_path="${filepath#src/}"  # 例: test/my_package_test/README.md

            # ディレクトリ名だけ取得
            dir_name=$(dirname "$relative_path")  # 例: test/my_package_test

            # 変換ルール
            if [[ $(basename "$filepath") == "README.md" ]]; then
              # README.mdならindex.mdに名前変更
              dest_file="docs/${dir_name}/index.md"
            else
              # それ以外は同じ名前でコピー
              dest_file="docs/${relative_path}"
            fi

            # コピー先のディレクトリを作成
            mkdir -p "$(dirname "$dest_file")"

            # コピー実行
            cp "$filepath" "$dest_file"

            echo "Copied $filepath to $dest_file"

            # もし同じ場所に .pages があればコピー
            if [[ -f "$(dirname "$filepath")/.pages" ]]; then
              cp "$(dirname "$filepath")/.pages" "$(dirname "$dest_file")/.pages"
              echo "Copied $(dirname "$filepath")/.pages to $(dirname "$dest_file")/.pages"
            else
              # 作成
              touch "$(dirname "$dest_file")/.pages"
              echo "Created $(dirname "$dest_file")/.pages"
              echo "nav:" > "$(dirname "$dest_file")/.pages"
              echo "    - index.md" >> "$(dirname "$dest_file")/.pages"
            fi
          done

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force

      - name: Debug
        run: |
          cat docs/behavior/nhk2025b_behavior/.pages
          git add .
          git commit -m "update .pages"
          git push origin mkdocs-deploy -f