name: Deploy MkDocs

on:
  push:
    branches:
      - 104-feat-readme-mkdocs-deploy 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Prepare README as index.md
        run: |
          mkdir -p docs
          cp README.md docs/index.md

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
